apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: development
  name: watchdog-k8s-sa

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: development
  name: watchdog-k8s-role
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
    verbs:
      - "get"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watchdog-k8s-role-binding
  namespace: development
subjects:
  - kind: ServiceAccount
    name: watchdog-k8s-sa
    namespace: development
roleRef:
  kind: Role
  name: watchdog-k8s-role
  apiGroup: rbac.authorization.k8s.io
