apiVersion: v1
kind: ServiceAccount
metadata:
  name: rundeck-sa
  namespace: support-tools

---

apiVersion: v1
kind: Secret
metadata:
  name: rundeck-sa-secret
  namespace: support-tools
  annotations:
    kubernetes.io/service-account.name: rundeck-sa
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: support-tools
  name: rundeck-role
rules:
  - apiGroups:
      - "*"
    resources:
      # Grant only CRUD operation in Pods and Jobs resources
      - "pods"
      - "pods/log"
      - "jobs"
      - "jobs/status"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rundeck-role-binding
  namespace: support-tools
subjects:
  - kind: ServiceAccount
    name: rundeck-sa
    namespace: support-tools
roleRef:
  kind: Role
  name: rundeck-role
  apiGroup: rbac.authorization.k8s.io
