apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rundeck-realm-properties-secret
  namespace: support-tools
data:
  # https://bcrypt-generator.com/
  # https://www.base64decode.org/
  realm.properties: YWRtaW46QkNSWVBUOiQyYSQxMCROcHlEc2JkelZhb3czdDhvRlNQLi91bGx1WVBpU1h3SmpPOENqdEFHTGc2LnRrcTNxTUhhUyx1c2VyLGFkbWlu

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rundeck-postgresql-secret
  namespace: support-tools
data:
  # Look at `rundeck-config-features.properties` file!
  ENC_PASSWORD: S05vc2VMcyF6Nn1NdXN0YWNoZVdwRG9nLEd4YnU=
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#database
  RUNDECK_DATABASE_PASSWORD: cG9zdGdyZXM=
  RUNDECK_DATABASE_USERNAME: cG9zdGdyZXM=
  EXECUTION_LOG_AWS_ACCESS_SECRET: cGFzc3dvcmQ=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rundeck-postgresql-configmap
  namespace: support-tools
data:
  # https://docs.rundeck.com/docs/administration/configuration/database/
  RUNDECK_DATABASE_DRIVER: "org.postgresql.Driver"
  RUNDECK_DATABASE_URL: "jdbc:postgresql://db-postgres-service.support-tools.svc.cluster.local:5432/postgres?autoReconnect=true&useSSL=true&allowPublicKeyRetrieval=true"
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#basic
  RUNDECK_GRAILS_URL: "http://localhost:8000"
  # It makes the project use the method `load_incluster_config` from the Python Kubernetes client.
  # https://github.com/willianantunes/rundeck-plugins-kubernetes/blob/8e2485396551a973000e3a52ae48a4fc282a0872/contents/common.py#L34-L36
  # https://github.com/kubernetes-client/python/blob/07fb11f2bc6a6356854e9dabcd7d65a62e849feb/kubernetes/base/config/incluster_config.py#L112-L121
  RD_CONFIG_ENV: "incluster"
  # https://github.com/rundeck-plugins/rundeck-s3-log-plugin
  EXECUTION_LOG_S3_BUCKET: "rundeck-postgresql-bucket"
  EXECUTION_LOG_S3_REGION: "us-east-1"
  EXECUTION_LOG_AWS_ACCESS_KEY: "root"
  EXECUTION_LOG_S3_ENDPOINT: "http://minio-s3-service:9000"
  EXECUTION_LOG_S3_PATH_STYLE: "true"

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rundeck-sqlserver-secret
  namespace: support-tools
data:
  # Look at `rundeck-config-features.properties` file!
  ENC_PASSWORD: S05vc2VMcyF6Nn1NdXN0YWNoZVdwRG9nLEd4YnU=
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#database
  RUNDECK_DATABASE_PASSWORD: UGFzc3dvcmQx
  RUNDECK_DATABASE_USERNAME: c2E=
  EXECUTION_LOG_AWS_ACCESS_SECRET: cGFzc3dvcmQ=
  realm.properties: YWRtaW46QkNSWVBUOiQyYSQxMCROcHlEc2JkelZhb3czdDhvRlNQLi91bGx1WVBpU1h3SmpPOENqdEFHTGc2LnRrcTNxTUhhUyx1c2VyLGFkbWlu

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rundeck-sqlserver-configmap
  namespace: support-tools
data:
  # https://docs.rundeck.com/docs/administration/configuration/database/mssql.html
  RUNDECK_DATABASE_DRIVER: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  RUNDECK_DATABASE_URL: "jdbc:sqlserver://db-sqlserver-0:1433;database=master"
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#basic
  RUNDECK_GRAILS_URL: "http://localhost:8001"
  RD_CONFIG_ENV: "incluster"
  # https://github.com/rundeck-plugins/rundeck-s3-log-plugin
  EXECUTION_LOG_S3_BUCKET: "rundeck-sqlserver-bucket"
  EXECUTION_LOG_S3_REGION: "us-east-1"
  EXECUTION_LOG_AWS_ACCESS_KEY: "root"
  EXECUTION_LOG_S3_ENDPOINT: "http://minio-s3-service:9000"
  EXECUTION_LOG_S3_PATH_STYLE: "true"

