apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rundeck-realm-properties-secret
  namespace: support-tools
data:
  # https://bcrypt-generator.com/
  # https://www.base64decode.org/
  realm.properties: YWRtaW46QkNSWVBUOiQyYSQxMCROcHlEc2JkelZhb3czdDhvRlNQLi91bGx1WVBpU1h3SmpPOENqdEFHTGc2LnRrcTNxTUhhUyx1c2VyLGFkbWlu

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rundeck-postgresql-secret
  namespace: support-tools
data:
  # Look at `rundeck-config-features.properties` file!
  ENC_PASSWORD: S05vc2VMcyF6Nn1NdXN0YWNoZVdwRG9nLEd4YnU=
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#database
  RUNDECK_DATABASE_PASSWORD: cG9zdGdyZXM=
  RUNDECK_DATABASE_USERNAME: cG9zdGdyZXM=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rundeck-postgresql-configmap
  namespace: support-tools
data:
  # https://docs.rundeck.com/docs/administration/configuration/database/
  RUNDECK_DATABASE_DRIVER: "org.postgresql.Driver"
  RUNDECK_DATABASE_URL: "jdbc:postgresql://db-postgres-service.support-tools.svc.cluster.local:5432/postgres?autoReconnect=true&useSSL=true&allowPublicKeyRetrieval=true"
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#basic
  RUNDECK_GRAILS_URL: "http://localhost:8000"

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rundeck-sqlserver-secret
  namespace: support-tools
data:
  # Look at `rundeck-config-features.properties` file!
  ENC_PASSWORD: S05vc2VMcyF6Nn1NdXN0YWNoZVdwRG9nLEd4YnU=
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#database
  RUNDECK_DATABASE_PASSWORD: UGFzc3dvcmQx
  RUNDECK_DATABASE_USERNAME: c2E=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rundeck-sqlserver-configmap
  namespace: support-tools
data:
  # https://docs.rundeck.com/docs/administration/configuration/database/mssql.html
  RUNDECK_DATABASE_DRIVER: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  RUNDECK_DATABASE_URL: "jdbc:sqlserver://db-sqlserver-0:1433;database=master"
  # https://docs.rundeck.com/docs/administration/configuration/docker.html#basic
  RUNDECK_GRAILS_URL: "http://localhost:8001"

