apiVersion: v1
kind: Service
metadata:
  namespace: support-tools
  name: rundeck-postgresql-service
spec:
  selector:
    app: rundeck-postgresql
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      # See `kind-config.yaml` to understand why I configured port 32000!
      nodePort: 32000
      port: 4440
      targetPort: web-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck-postgresql-deployment
  namespace: support-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck-postgresql
  template:
    metadata:
      labels:
        app: rundeck-postgresql
    spec:
      serviceAccountName: rundeck-sa
      containers:
        - name: rundeck-postgresql
          image: rundeck-k8s
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rundeck-realm-properties
              mountPath: /home/rundeck/server/config/realm.properties
              subPath: realm.properties
          envFrom:
            - configMapRef:
                name: rundeck-postgresql-configmap
            - secretRef:
                name: rundeck-postgresql-secret
          ports:
            - name: web-server
              containerPort: 4440
          livenessProbe:
            httpGet:
              path: /
              port: 4440
              scheme: HTTP
            initialDelaySeconds: 500
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: 4440
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 350m
              memory: 1250Mi
            limits:
              cpu: 700m
              memory: 1800Mi
      volumes:
        - name: rundeck-realm-properties
          secret:
            secretName: rundeck-realm-properties-secret

---

apiVersion: v1
kind: Service
metadata:
  namespace: support-tools
  name: rundeck-sqlserver-service
spec:
  selector:
    app: rundeck-sqlserver
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      # See `kind-config.yaml` to understand why I configured port 32001!
      nodePort: 32001
      port: 4440
      targetPort: web-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck-sqlserver-deployment
  namespace: support-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck-sqlserver
  template:
    metadata:
      labels:
        app: rundeck-sqlserver
    spec:
      serviceAccountName: rundeck-sa
      containers:
        - name: rundeck-sqlserver
          image: rundeck-k8s
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rundeck-realm-properties
              mountPath: /home/rundeck/server/config/realm.properties
              subPath: realm.properties
          envFrom:
            - configMapRef:
                name: rundeck-sqlserver-configmap
            - secretRef:
                name: rundeck-sqlserver-secret
          ports:
            - name: web-server
              containerPort: 4440
          livenessProbe:
            httpGet:
              path: /
              port: 4440
              scheme: HTTP
            initialDelaySeconds: 500
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /
              port: 4440
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 1000m
              memory: 1250Mi
            limits:
              cpu: 1500m
              memory: 1800Mi
      volumes:
        - name: rundeck-realm-properties
          secret:
            secretName: rundeck-sqlserver-secret
            items:
              - key: realm.properties
                path: realm.properties
