kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
    extraPortMappings:
      - containerPort: 32000
        # Rundeck web server postgresql
        hostPort: 8000
        listenAddress: "127.0.0.1"
      - containerPort: 32001
        # Rundeck web server sqlserver
        hostPort: 8001
        listenAddress: "127.0.0.1"
      - containerPort: 30000
        # PostgreSQL socket port
        hostPort: 5432
        listenAddress: "127.0.0.1"
      - containerPort: 30001
        hostPort: 1433
        listenAddress: "127.0.0.1"
  - role: worker
    image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
