services:
  # Don't publish the RPC port to the host unless you know what you're doing
  # If you don't publish you're more protected from remote attacks
  bitcoin-core-middleware:
    build:
      context: .
    volumes:
      - "./middleware:/home/bitcoin/.bitcoin/"
    environment:
      - UID=$UID
      - GID=$GID
    networks:
      - web
      - no-internet
  bitcoin-core-wallet:
    build:
      context: .
    volumes:
      - "./wallet:/home/bitcoin/.bitcoin/"
    environment:
      - UID=$UID
      - GID=$GID
    networks:
      - no-internet

networks:
  web:
    driver: bridge
  no-internet:
    driver: bridge
    internal: true # https://docs.docker.com/compose/compose-file/06-networks/#internal
